CS\AperoBundle\Entity\Soiree:
    type: entity
    table: null
    repositoryClass: CS\AperoBundle\Entity\SoireeRepository
    manyToOne:
        users:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
        description:
            type: string
        paiement:
            type: integer
        date:
            type: datetime
        nombreparticipant:
            type: integer
    lifecycleCallbacks: {  }
