CS\AperoBundle\Entity\Soiree:
    type: entity
    table: null
    repositoryClass: CS\AperoBundle\Entity\SoireeRepository
    manyToMany:
        users:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: soirees

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
        description:
            type: string
        paiement:
            type: integer
        date:
            type: datetime

    lifecycleCallbacks: {  }
