CS\AperoBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: CS\AperoBundle\Entity\UserRepository
    manyToMany:
        participants:
            targetEntity: Soiree
            inversedBy: users
            joinTable:
                name: users_soirees
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    soiree_id:
                        referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fileds:
        prenom:
            type: string
        nom:
            type: string
        age:
            type: integer
        taille_foie:
            type: integer
    lifecycleCallbacks: {  }
