cs_apero_homepage:
    path:     /hello/{name}
    defaults: { _controller: CSAperoBundle:Default:index }

ajout:
    path:     /soiree/add
    defaults: { _controller: CSAperoBundle:Soiree:index }

show:
    path:     /soiree/show/{id}
    defaults: { _controller: CSAperoBundle:Soiree:show }

list:
    path:   /soiree
    defaults: { _controller: CSAperoBundle:Soiree:list }