cs_apero_homepage:
    path:     /hello/{name}
    defaults: { _controller: CSAperoBundle:Default:index }

ajout:
    path:     /soiree/add
    defaults: { _controller: CSAperoBundle:Soiree:index }

show:
    path:     /soiree/{id}/show
    defaults: { _controller: CSAperoBundle:Soiree:show }

list:
    path:   /soiree
    defaults: { _controller: CSAperoBundle:Soiree:list }

soiree_inscription:
    path: /soiree/{id}/inscription
    defaults: { _controller: CSAperoBundle:Soiree:inscription}