<?php

namespace CS\AperoBundle\Entity;

/**
 * Utilisateur_soireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateur_soireeRepository extends \Doctrine\ORM\EntityRepository
{
}
